### PR TITLE
Pull request: more than one push

### PR DESCRIPTION
**Pull request by andrewschultz**
Sorry about the pulls lumped together, again. I'm still learning--I never used source control much in testing.

I didn't realize I needed to make a pull request after each push. I thought I could do so individually. But I think it makes sense now. I may put in another quick change or two for other issues just to check things.

I'm worried the shift-arrowing is a bit wobbly but I tested it and have test files for everything.

### CODE REVIEW

**Comment by JasonLautzenheiser** [comment]
@andrewschultz with #165, it seems that the SHIFT-Arrows work, but not the  SHIFT numberpads keys....nor does the CTRL seem to do anything, though it looks like there is some code that might be in there for that.    Does what you implemented differ from what #165 says?  or am I missing something?

All the other items look good....I'll merge the pull request once I understand #165

**Comment by andrewschultz** [comment]
This is a tricky one. sorry for the delay getting back to you. I should have explained a lot more, as there are test cases where I assumed a few things and didn't write them out.

One problem I had is: Windows seems to process the numpad oddly. For instance, if I type shift-Num8 or shift-Num7 with the NumLock on, it doesn't register the shift. I can see this stepping through the debug code in canvas.cs. You can look for Keys.NumPad7 or Keys.Home and put a breakpoint there: ModifierKeys will be None with NumLock on, but it will register with NumLock off.

Some googling says that this can differ between keyboards. But in any case, it's put a damper on smooth implementation of shift-(direction). I added code that allows shift-(home/pageup/end/down) to go to diagonal connectors, but it doesn't feel as good as it can be.

So I wrote up this spreadsheet. The thing is, we do lose some functionality, but it *seems* (to me) relatively random and accidental and counterintuitive. That doesn't mean I can't do better.

https://docs.google.com/spreadsheets/d/1e9_Q53DYzMozsniJURlijJSsXm8b18pITwwRZUSNsd8/edit#gid=0

Differences are in italics. Comment/change wherever you want/need.

I think Trizbort's UI has a problem with the numpad being different from the arrow keys. This feels counterintuitive, but what Genstein wanted to do makes sense. He wanted the user to be able to use arrows to move a room or move between rooms.

However, having used trizbort for a while, and having been frustrated by the numpad being on/off etc., I think it might be better to normalize the arrows and numpads into the same code and allow the user to decide with a global option (maybe toggle with an F key or something) whether

1 ctrl-arrows = new room, arrows = move room
or
2 arrows = new room, ctrl-arrows = move room

Especially since I've found that a lot of times I really only just make new rooms & then I adjust them later.

**Comment by JasonLautzenheiser** [comment]
I put some notes on the spreadsheet....I'll have to give it some more thought, I think the keys are close to what they should be....we can clean up some, but I don't think we should give the users too many options to change the keys that perform a function.  If we decide that Ctrl-Arrows is new room, then that's that it should be.    Will need to give this some thought before we really do anything.  I'm going to merge this in as I don't want to hold up the other fixes for this one...

**Comment by andrewschultz** [comment]
Thanks again for helping me through this. I think in the future I will have one branch for small low-risk changes and one for big ones, now I've contributed several pulls of varying complexity.

And I'll give a poke if I think I can't see any way around a hack. (Also, I'll remember to PUSH after a GIT PULL command. I'm still learning & keeping a cheat sheet. But a lot of things I previously overheard/read about source control *mean* a lot more now, and that's big, not just technically but just so I understand others' roles.)

**Pull request merged**
