### PR TITLE
Zoom plus testfiles

### PR DESCRIPTION
**Pull request by andrewschultz**
I think I goofed with Github and I think I somehow didn't send this pull request like I meant to. There's no rush for it, of course. But it addresses the issues that caused the merge-reverse in #340, with some test files thrown in.

### CODE REVIEW

**Comment by JasonLautzenheiser** [comment]
Just pushed out the new release literally 5 minutes before you  pushed this up there.  :)  Will be sure to get this up for the next release.

**Comment by andrewschultz** [comment]
No problem! The release was what prompted me to do this! I thought I *had* pushed it this morning, but it looks like there still are a few things I need to learn about pushing correctly in git.

**Comment by JasonLautzenheiser** [comment]
ok...I think I may have misunderstood what this pull request was meant to do.   When I use this with my files or with the test files provided...it starts off way to zoomed in.  Take a look at the screenshot....it's zoomed to 20% it really doesn't need to be anywhere near that far.

I may end up reverting this, unless you see an issue that I'm not.

image

**Comment by andrewschultz** [comment]
This looks like the test file where I gave the super wide margins. 17-by-17-1200-margins.trizbort? In which case, that's expected behavior, because it's basically those 4 rooms with big margins all around, and nothing else. I wanted test files that made it clear we took margins into account if they existed.

The map you sent me is at 63% which seems reasonable--the margins make it so we can see the dangling connections. But If you have another file of your own that zooms too far out, or that shows differently on your own computer, then that is *not* okay. Put it on gist or wherever.


It's also quite possible I may have merged some bad code--I know I did some stash/unstash after testing something that worked pretty successfully.

**Comment by JasonLautzenheiser** [comment]
It's doing it for all files I've tried....the test file I sent you originally now looks like this.

image

I tried the 17 by 17 which I assume is no margins and it looks the same as the one above

**Comment by andrewschultz** [comment]
Hmm. Can you take a look at your app settings? I defined big margins (1200 h/v) there and am now seeing what you're seeing, where all docs I open are too small. Tools::App Settings::App defaults in the lower left.

If changing map-specific margins is unexpectedly also changing app settings, then obviously need fixing, and we need to figure why that's the case. And I'd be glad to poke around for possible ways this happened (e.g. see what code changes the general map settings.)

**Comment by JasonLautzenheiser** [comment]
Well, my margins were set to 100 x 1000.  I changed them down, turned margins off and tried all different kinds of combos...and I'm still seeing the issue like above.  Something strange is going on, just can't quite put my finger on it.   If you have time to poke around, please do.

**Comment by andrewschultz** [comment]
Hmm, can you send me your settings file, then? I think you have my gmail.

**Comment by andrewschultz** [comment]
Thanks! Using your settings doesn't show any difference, but I've built a version of the executable which tracks the values in the structure. Could I send that over?

Also, would it be better to use email for future files or keep responding in this thread?

**Comment by JasonLautzenheiser** [comment]
Email is fine

**Pull request merged**
