### PR TITLE
Automap resectioning + initial test suite

### PR DESCRIPTION
**Pull request by andrewschultz**
connection_styles.png is updated to show more options, as is the text below.

Automap is in its own section. <h[0-9]> tags are checked as is general outlining. The <h> tag changes were responsible for a big chunk of the differences.

### CODE REVIEW

**Comment by JasonLautzenheiser** [comment]
Just a question....I see in the ignore file that you are leaving out the trizbort files in the testing folder.   Any reason why we wouldn't want them included in the repository for testing purposes?

**Comment by andrewschultz** [comment]
No problem--they're in the zip file and I thought that they might become too numerous. It seemed like the zip file would be cleaner, but I don't know.

**Comment by JasonLautzenheiser** [comment]
Yeah, I'm not sure it would be a problem....the trizbort files aren't that large....people might want to get into the repository and grab and individual file that highlights something they are trying to do / mimic in their own map so it might be nice to see them listed individually instead of all in a zip.   Plus git will handle changes to them easier (storing more efficiently) the changes between updates to individual trizbort files better than if it was all in one zip.

**Comment by andrewschultz** [comment]
Okay, I'll send in a new one just now. It'll have a few more test cases.

I think it's best to keep the ZIP file first, so people can download everything.

If we ever get to 250 unit tests or whatever, we can reconsider. But maybe that is worrying too far ahead.

**Pull request closed without merging**
