### PR TITLE
Bug fixes and feature requests: #188, #205, #206

### LINKED ISSUE #205: ctrl-d = delete all connectors from a room
This is fixed locally. I think it's a useful feature.

### LINKED ISSUE #206: ctrl- [] causes a port to "disappear"
I didn't understand how ports worked, so my port rotation caused the from-port to "disappear" when I twiddled things. It's not really gone--it's just hidden behind another port.

So obviously I need to rework this. There is a workaround--saving and reopening--but the user shouldn't have to.

### PR DESCRIPTION
**Pull request by andrewschultz**
27 files is a lot of changed files, so let's break it down.

Code changes:

AppSettingsDialog.designer.cs / AppSettingsDialog.cs: added granularity feature and did some reorganizing to gain space
Canvas.cs: keycodes for fixes to #205 and also the beginning of #188. I put in a bit of trickery that allows someone to adjust granularity on the fly. ctrl-\, with ctrl-shift-\ showing the new granularity, toggles from 4 rooms to 8 to 16.
Connection.cs: fixed #206
Room.cs: fixed #205 and the beginning of #188, which only does one room so far.
Settings.cs: #188's granularity settings saved

Granularity says, how many exits are available if we push ctrl-\ to reorganize a room? 4 = NSEW, 8 = diagonals, 16 = all ports.

Test document changes:
Added test documents to test out granularity of 4, 8 and 16.

testsync.pl: added a line to prompt rerunning with -r if everything is okay
manual.bat: added auto-adjust* trizbort test files
auto-adjust* trizbort test files test granularity

Sample file changes:
samples/*: added margins to all trizbort files and re-saved as PDF

### CODE REVIEW

**Comment by JasonLautzenheiser** [comment]
Just as  a note @andrewschultz I'm resolving some merging conflicts....so in general it would be easier if we had smaller pull requests.  I don't mind more pull requests as it makes it easier to test and to merge.  In general, each issue fix / feature add, could be it's own pull request.

**Comment by andrewschultz** [comment]
Yeah, I agree. That makes a lot of sense. Both seem like they have their own inconveniences, but if there are regressions or bugs, they will be easier with one pull per issues.

Next time if I'm on a roll and it's late, I'll slow things down and check off.

Also I want to make sure I have my branch fully updated with the main one. Sorry for any additional work this caused.

**Comment by JasonLautzenheiser** [comment]
No worries....at work we've gone to the pull request per issue / feature and it has really streamlined our development.  A little bit of overhead creating the pull requests, but it has gone a long way to helping get quality code into the master branch.  I manage the team of developers so I get to review most of the pull requests and it has made my job much easier.

**Comment by JasonLautzenheiser** [comment]
@andrewschultz I merged this in, but you may want to pull the latest into your repo and test that I didn't break anything while merging.  I've found a few small issues (not worth holding up the merge), that I'll add issues for soon.

**Comment by andrewschultz** [comment]
Thanks! I pulled the latest code and I'm going to try again in a few minutes pushing a few small assorted changes I have. I'm worried the zip file of test files would be hard to merge, but we'll see how it goes. I thought of some changes as "oh, it's a 1 line fix not worth worrying about." & this will help you keep the bugs straight too.

**Pull request merged**
