### PR TITLE
Solution for #459

### PR DESCRIPTION
**Pull request by Nyun0**
This is my solution proposition for #459 

The tooltip is being re-drawn when it is shown upon panning and moving the element. This causes a rather noticeable tooltip flicker, especially when snap-to-grid is turned off or when panning.

Known "issues":
1. flicker
2. when moving the element or panning in a way that the element is not visible on the canvas, the tooltip "stays" near the visible edge

### CODE REVIEW

**Comment by JasonLautzenheiser** [comment]
So in testing this, the tooltip does move with the room now, but the flicker is kinda annoying.  But what's worse is the map itself is not panned smoothly.   The tooltip will move, then the map kinda "jumps" in behind it.    I'd almost rather have it the way it is unless we can clean this up some.

**Comment by Nyun0** [comment]
The other way (which I tested first) is to hide the tooltip upon moving an element or panning. The results are really nice, and I was hesitating to go with it as a solution to be honest.

**Comment by Nyun0** [comment]
I will create a separate merge request with the second solution - I think it will be better to hide the tooltip instead of redrawing it every frame.

**Comment by Nyun0** [comment]
@JasonLautzenheiser, now it should be a lot smoother with [f5abb90](https://github.com/JasonLautzenheiser/trizbort/pull/461/commits/f5abb903af5d79157032486fc14b49df1b0e50b2)

**Comment by JasonLautzenheiser** [comment]
@Nyun0 Sorry for the delay on looking at the latest....I will do so hopefully later today.

**Pull request merged**
